### DISCUSSION TITLE
Tips on speeding up database build times?

### DISCUSSION THREAD

**Discussion by why-does-ie-still-exist** [ludwig-ai/ludwig#1110] [Q&A] [answered]
I've been doing some image classification using Ludwig, and so far I've gotten around 75% accuracy. I want to try more configurations for the model, but **every time I change my configuration file** it gets stuck on `Building dataset(it may take a while)` For me, this "a while" is 10-15 minutes on a colab remote machine, which hamstrings iteration.
I suspect this is due to the fact that I have to preprocess every image through Ludwig each run, because the hash of the config file doesn't match (even if it has the same preprocessing parameters) and so the database would have to be rebuilt. **If I did the pre-processing myself, would this step be faster?**

An example of what one of my config files looks like:
```
input_features:
    -
        name: image_path
        type: image
        encoder: stacked_cnn
        preprocessing:
        resize_method: interpolate
                width: 128
                height: 128

output_features:
    -
        name: class
        type: category
```

For reference, I have about 105 12MP images that I'm preprocessing each run. **Should it take this long?**
