### DISCUSSION TITLE
Getting started question

### DISCUSSION THREAD

**Discussion by ianmuscat** [ludwig-ai/ludwig#1229] [Q&A]
Hi there, I'm super new to ML and Ludwig, so I'm almost certainly missing something. I'm trying to complete an example in the getting started guide, but I'm stuck when it comes to getting predictions to work.

I'm using the `epinions-1.csv` (CSV file with a `class` and a `text` column) as suggested in the getting started guide and I'm running Ludwig using the official Docker container. The following is my configuration.

```
input_features:
- name: text
  type: text
  level: word
  encoder: parallel_cnn
output_features:
- name: class
  type: category
```

First off I start training using the `experiment` command. That seems to work and outputs a model. However when I try to use the following `predict` command on **the same data** with the `class` column removed (same CSV, just a single column), I don't get any CSVs with predictions as the docs seem to indicate I should. `prediction.shapes.json` contains an empty object and the NPY files also seem empty when loaded with `numpy.load`.

```
ludwig predict --dataset /data/epinions-1-text.csv --data_format csv --model_path /data/results/experiment_run/model --output_directory /data/predictions
```

Any idea what I'm doing wrong? Thanks! 🙏
