### DISCUSSION TITLE
Is possible  to make ludwig  configuration for translation from one  language to other

### DISCUSSION THREAD

**Discussion by PeterPirog** [ludwig-ai/ludwig#1630] [Q&A] [answered]
I wonder if possible to make ludwig configuration for translation from one language to other.
I suppose it should look like that:

```
input_features:
    -
        name: text_language1
        type: text
        level: word
        encoder: bert
        tied_weights: null
        pretrained_model_name_or_path: bert-base-uncased
        reduced_output: cls_pooled
        trainable: false

output_features:
    -
        name: text_language2
        type: text

        decoder: bert
       pretrained_model_name_or_path: bert-base-for-language2
```
I suppose that the configuration for chat bot should be similar but there is the same language transformer for input and output.

**Comment by justinxzhao** [comment, marked as answer]
The answer is yes (on v0.4/tensorflow).

For a text2text translation task, what you've outlined is essentially it. We're working on reimplementing text decoders in Pytorch, so this functionality should be available in the next 0.5 pytorch-based release as well.

```
input_features:
    -
        name: text_language1
        type: text
        encoder: bert
        pretrained_model_name_or_path: bert-base-uncased
        trainable: false

output_features:
    -
        name: text_language2
        type: text
        decoder: lstm
        beam_size: 5
```

We don't support pre-trained text decoders, but you should be able to get something reasonable with a basic `lstm` or `rnn` decoder.
