### DISCUSSION TITLE
What is the difference between preprocessing tokenizer and input_features tokenizer?

### DISCUSSION THREAD

**Discussion by farazk86** [ludwig-ai/ludwig#2230] [Q&A] [answered]
Hi,

I'm trying to understand the difference between the following two configurations:

```yaml
"input_features": [
        {
            "name": "both_text",
            "type": "text",
            "preprocessing": {
                "tokenizer": "space",
            },
            "encoder": "rnn",
            "cell_type": "lstm",
            "num_layers": 8,
            "reduce_output": None,
        }
    ],
    "preprocessing": {
        "split_probabilities": [0.8, 0.1, 0.1],
    },
```
and
```yaml
"input_features": [
        {
            "name": "both_text",
            "type": "text",
            "encoder": "rnn",
            "cell_type": "lstm",
            "num_layers": 8,
            "reduce_output": None,
        }
    ],
    "preprocessing": {
        "split_probabilities": [0.8, 0.1, 0.1],
        "text": {
          "tokenizer": "space",
        },
    },
```

They both appear to be tokenizing the input_text based on ``space``. However both produce different results?

Can anyone please tell me whats the difference between using ``tokenizer`` in ``preprocessing`` or ``input_features``? If I want my input text to be space tokenized which one should I use?

Also, if I use tokenizer setting in both ``input_features`` and ``preprocessing`` I get an error at evaluation stage:

> 'Cannot mix NumPy dtypes float64 and float32', 'Conversion failed for column labels_probabilities with type object'

Thanks
