### DISCUSSION TITLE
Understanding LLM finetuning logs

### DISCUSSION THREAD

**Discussion by dotXem** [ludwig-ai/ludwig#3943] [Q&A]
Hello there, I am trying to use Ludwig for a LLM finetuning task, and I have two questions regarding the training logs I get:
1. the loss value displayed when doing an epoch do not reflect the loss in the report at the end of the epoch
2. the generated examples after an epoch are complete gibberish, while doing generation at the end of the training works much better

Here is my config:
```
f"""
model_type: llm
base_model: {model_name}

input_features:
  - name: input
    type: text

output_features:
  - name: output
    type: text
"""+"""
prompt:
  template: |
    [INST] <<SYS>>
    You are a League of Legends expert. Here is the state of a game with the time, the blue team gold advantage at the start of the time, the events that happened in the next minute following the time.
    Gold advantage is expressed in hundreds of gold. Events are encoded following the format: `side event_type`. For instance, `blue p` means that a blue player killed a red player. Here are the possible event types: `p` for player kill, `t` for tower kill, `i` for inhibitor kill, `d` for drake kill, `r` for rift herald kill, `b` for baron kill, `n` for nexus kill which signifies that the game has ended by the victory of the team destroying it.
    Answer with the gold advantage of the blue team at the end of the minute using the available information. It should be single number (positive or negative).
    Example: 
    Input: Time: 15:00; Blue team gold advantage start: 5; Events: blue r,blue p,red t,red p,blue t,red t.
    Answer: -5
    <</SYS>>
    {input} [/INST]
generation:
  temperature: 0.1
  max_new_tokens: 4

adapter:
  type: lora

quantization:
  bits: 4

preprocessing:
  split:
    type: random
    probabilities:
    - 0.9 # train
    - 0.05 # val
    - 0.05 # test

trainer:
  type: finetune
  epochs: 5
  batch_size: 1
  eval_batch_size: 2
  gradient_accumulation_steps: 16
  learning_rate: 0.00001
  learning_rate_scheduler:
    warmup_fraction: 0.03
"""
```

The code that runs the training and does the inference afterwards (where `qlora_fine_tuning_config` is the config above):
```
model = LudwigModel(config=qlora_fine_tuning_config, logging_level=logging.INFO)
results = model.train(dataset=df)

predictions = model.predict(testset, generation_config={'temperature': 0.1, 'max_new_tokens': 4})[0]
for input_with_prediction in zip(testset['input'],predictions['output_response'],testset['output']):
  print(f"Input: {input_with_prediction[0]}")
  print(f"Generated Output: {input_with_prediction[1][0]}")
  print(f"Expected Output: {input_with_prediction[2]}")
  print("\n\n")
```

> 1. the loss value displayed when doing an epoch do not reflect the loss in the report at the end of the epoch

During the training of the epoch, loss is displayed with value of 0.169; but in the report it's a complete different value. What am I not understanding?

`Training: 100%|█████████████████████████████████████| 4500/4500 [1:55:32<00:00,  1.56s/it, loss=0.169]`

```
╒═══════════════════════╤════════════╤══════════════╤════════════╕
│                       │      train │   validation │       test │
╞═══════════════════════╪════════════╪══════════════╪════════════╡
│ bleu                  │     0.0000 │       0.0000 │     0.0000 │
├───────────────────────┼────────────┼──────────────┼────────────┤
│ char_error_rate       │   453.6102 │     432.1727 │   467.5882 │
├───────────────────────┼────────────┼──────────────┼────────────┤
│ loss                  │     1.8352 │       1.7845 │     1.7323 │
```

> 2. the generated examples after an epoch are complete gibberish, while doing generation at the end of the training works much better

Here are one generated example during evaluation step (all other examples look like this)

```
--------------------
Input: [INST] <<SYS>>
You are a League of Legends expert. Here is the state of a game with the time, the blue team gold advantage at the start of the time, the events that happened in the next minute following the time.
Gold advantage is expressed in hundreds of gold. Events are encoded following the format: `side event_type`. For instance, `blue p` means that a blue player killed a red player. Here are the possible event types: `p` for player kill, `t` for tower kill, `i` for inhibitor kill, `d` for drake kill, `r` for rift herald kill, `b` for baron kill, `n` for nexus kill which signifies that the game has ended by the victory of the team destroying it.
Answer with the gold advantage of the blue team at the end of the minute using the available information. It should be single number (positive or negative).
Example:
Input: Time: 15:00; Blue team gold advantage start: 5; Events: blue r,blue p,red t,red p,blue t,red t.
Answer: -5
<</SYS>>
Time: 11:00; Blue team gold advantage start: -6; Events: none. [/INST]
Output: #adALL
<_

 are a member of Legends player.
 are your chance of the game.  following in the players team is,, the end of the game, the blue that happened during the game , the start,

 advantage at the in the of gold.
 are expressed as the format:
<:`type target
 example, `blue killing means that the player player died a blue player.
 is the possible events types: `p` for player kill, `t` for tower kill, `i` for inhibitor kill, `b` for dragonrake kill, `b` for redift herald kill, `b` for baron kill. `s` for nexus kill. endsifies the the game is ended. the death of the side that the.

swer the the team advantage of the blue team at the end of the minute following the format events.
 can be noted-.integeritive or negative).

:
1``1  = 10,00, Blue gold gold advantage at of 10 Events: ` p; red p,red p,red p,blue p,blue p, OutputOutputswer: 1
InputNAINST>>
:115:00
 BlueTeam gold advantage start: 1; Events: blue ->
1IMP] - -6 -
--------------------
```

It's nowhere close to what I am trying to achieve, but when doing inference after the training, I actually get decent results.

````
Input: Time: 29:00; Blue team gold advantage start: -71; Events: red p,blue p,blue p,blue p,red p,blue p,blue t.
Generated Output: -64
Expected Output: -48

Input: Time: 30:00; Blue team gold advantage start: -48; Events: blue t,blue b,red p.
Generated Output: -52
Expected Output: -26

Input: Time: 31:01; Blue team gold advantage start: -26; Events: red p,red i.
Generated Output: -30
Expected Output: -34

Input: Time: 32:01; Blue team gold advantage start: -34; Events: none.
Generated Output: -34
Expected Output: -35
```

Overall model seems to train, but the training metrics and logs seem to be completely off. Maybe you can shed some light into this?
