### DISCUSSION TITLE
Truncate (or Padding) Input

### DISCUSSION THREAD

**Discussion by bifterciabata** [ludwig-ai/ludwig#4023] [General]
Hi, I use ludwig version 0.10.4. I try to use for finetuning paraphrase task using indonesian dataset.
Here is my prompt (in Indonesian)

```
prompt:
  template: |
    Instruction: Parafrasekan kalimat yang diberikan dalam Bahasa Indonesia dengan mempertahankan makna asli tetapi menggunakan kata-kata dan struktur yang berbeda.

    Input: {input}

    Response:

````

But in validation I got this

<img width="930" alt="image" src="https://github.com/user-attachments/assets/6fe3e745-3b0f-41cd-be55-5c71849b1e56">

My question is:
Why there is ! before instruction?
Is it because padding? and translated to `!` ?

In preparation log I saw 
`No padding token id found. Using 0 as pad token id.` Can we modify this padding token?

Thank you
