### ISSUE TITLE
Using validation_metric: accuracy doesn't work.

### ISSUE THREAD

**Issue by mangleddata** [ludwig-ai/ludwig#1063]
My trainer below throws an error ``` ValueError: The specified metric accuracy is not valid. Available metrics for combined output feature are: ['loss'] ```.  Any idea why ?

```
output_features:
- loss:
    class_weights:
    - 0
    - 1.0
    - 1.0564683477214132
    - 1.7746876320395968
    weight: 1
  name: category1
  type: category
- loss:
    class_weights:
    - 0
    - 1.0
    - 1.0691449327530351
    - 3.091889845746191
    weight: 1
  name: category2
  type: category
training:
  batch_size: 32
  decay: true
  early_stop: 5
  epochs: 100
  learning_rate: 1.0e-05
  regularization_lambda: 0.001
  regularize: true
  validation_field: combined
  validation_measure: accuracy
  validation_metric: accuracy
```
