### ISSUE TITLE
reduce_dependencies for numerical values

### ISSUE THREAD

**Issue by humanID** [ludwig-ai/ludwig#1079]
I am trying to predict two numerical outputs of the same value measured at different time intervals. One is the final value, whereas the other one is an intermediate value, always smaller than the final one. Is there a way of telling Ludwig this relationship, besides defining a dependency?

```
output_features:
-
 name: final_value
 type: numerical
- 
  name: intermediate_value
  type: numerical
  dependencies: 
   - final_value
```
**Questions:**

1. I saw that I can **_reduce_dependencies_**, but I'm not sure if this declaration should sit with the _intermediate_value_ or the _final_value_. 

2. A brief explanation of what _sum_, _mean_, _max_, _concat_, and _last_ do in this context would also be greatly appreciated.

3. Bonus round: if I would have a third intermediate value (or more), should I make all of them dependent on the next measured value (1st_intermediate_value will depend on the 2nd_intermediate_value which will depend on the final_value)?

Thank you. 

PS Sorry, I wouldn't have bothered you with these questions, but the link toward the community is broken. You should also be aware of a minor typo on your website: search for **_9second_** in the [User Guide](https://ludwig-ai.github.io/ludwig-docs/user_guide/). It should read **_(second_**. There are 13 occurrences of it.
