### ISSUE TITLE
Error training a model for Named Entity Recognition Tagging

### ISSUE THREAD

**Issue by plantroots** [ludwig-ai/ludwig#1104]
I am trying to train a NER model with this configuration:

```
input_features:
    -
        name: utterance
        type: text
        level: word
        encoder: rnn
        cell_type: lstm
        reduce_output: null
        preprocessing:
          word_tokenizer: space

output_features:
    -
        name: tag
        type: sequence
        decoder: tagger
```

The error that I am seeing is:

```
StagingError: in user code:

    /usr/local/lib/python3.6/dist-packages/ludwig/models/ecd.py:176 train_step  *
        model_outputs = self((inputs, targets), training=True)
    /usr/local/lib/python3.6/dist-packages/ludwig/models/ecd.py:118 call  *
        decoder_outputs = decoder(
    /usr/local/lib/python3.6/dist-packages/ludwig/features/base_feature.py:271 call  *
        logits = self.logits(logits_input, target=target, training=training)
    /usr/local/lib/python3.6/dist-packages/ludwig/features/sequence_feature.py:243 logits  *
        inputs,
    /usr/local/lib/python3.6/dist-packages/ludwig/decoders/sequence_decoders.py:785 _logits_training  *
        return self.call(inputs, training=training, mask=mask)
    /usr/local/lib/python3.6/dist-packages/ludwig/decoders/sequence_decoders.py:774 call  *
        LENGTHS: inputs[LENGTHS]
```

The input data looks like this:
```
{
  'utterance': 'Jury awards more than $ 37M to family of Korryn Gaines in civil case against Baltimore County', 
  'tag': 'O O O O O O O O O PERSON PERSON O O O O LOCATION LOCATION'
}
```
OS: Ubuntu 18.04.5 LTS
Ludwig version: 0.3.3
Python version: 3.6.9
