### ISSUE TITLE
How Could I share the encoder with in Siamese Networks

### ISSUE THREAD

**Issue by ericxsun** [ludwig-ai/ludwig#1180]
**Is your feature request related to a problem? Please describe.**

Define the structure with the following `config.yaml`:

two encoders are given in the `input_features`, and both using the `stacked_cnn` module. Is it possible to share the `stacked_cnn`(I mean, share stacked_cnn struct and all weights) and How? 

Any idea will be highly appreciated.

```
input_features:
    -
        name: image_path_1
        type: image
        encoder: stacked_cnn
        preprocessing:
          width: 28
          height: 28
          resize_image: true
    -
        name: image_path_2
        type: image
        encoder: stacked_cnn
        preprocessing:
          width: 28
          height: 28
          resize_image: true
        tied_weights: image_path_1

combiner:
    type: concat
    num_fc_layers: 2
    fc_size: 256

output_features:
    -
        name: similarity
        type: binary
```
