### ISSUE TITLE
How to provide class weights for an imbalanced datasets?

### ISSUE THREAD

**Issue by farazk86** [ludwig-ai/ludwig#1188]
Hi,

I have a fairly imbalanced dataset. I am using this to learn a feature and am replying on dependency learning to get better results, i.e. [as explained here](https://ludwig-ai.github.io/ludwig-docs/user_guide/#output-features-dependencies), I have a coarse feature, who identification helps in identifying a fine feature. 

Below is my model configuration for the above goal:
```yaml
input_features:
    -
        name: nhl
        type: sequence
        encoder: rnn
        cell_type: lstm
        num_layers: 4
        reduce_output: null

output_features:
    -
        name: mode
        type: category
        num_fc_layers: 2
    -
        name: volpiano
        type: sequence
        decoder: generator
        cell_type: lstm
        attention: bahdanau
        num_fc_layers: 1
        dependencies:
            - mode
        loss:
            type: sampled_softmax_cross_entropy
```

The problem is (or at least in my opinion) that the ``mode`` output on which the ``volpiano`` output depends is very imabalanced. Below is the distribution of this feature:

![image_2021-05-30_021653](https://user-images.githubusercontent.com/33456896/120088885-19595880-c0ed-11eb-993d-5162c3c2d11f.png)

As can be seen mode ``8, 1 and 7`` are much better represented than the other categories in the dataset.

Is there any way to perform weighted learning to reduce this class imbalance? I found this issue discussing this as well: https://github.com/ludwig-ai/ludwig/issues/615 and know that I can use ``class_weights`` to achieve this.. but am not very use how to do this?

How do I find the ``class_weights`` values? and if I have this many classes, how can I be sure which weight to associate with which? I mean if I write: ``class_wrights: [8, 7, 6, 6, 3, ....]`` how can I be sure which weight is associated with which label?

Thanks
