### ISSUE TITLE
[automl] Binary column type not detected for floats

### ISSUE THREAD

**Issue by tgaddair** [ludwig-ai/ludwig#1511]
For example, the titanic dataset has values like `1.0` and `0.0`. These can correctly be interpreted as binary values `1` and `0` respectively, but the auto detect system is treating this as a categorical feature.

**Comment by PeterPirog** [comment]
@tgaddair I thinh that:
`output_features:
    -
        name: Survived
        type: binary`
and
`output_features:
    -
        name: Survived
        type: category`

are interpret similar, if you want numeric output you need of course:
`output_features:
    -
        name: Survived
        type: numeric`

but for me the question is **how to  configure sigmoid layer as  output to probaability value result?** Equivalent for:
`pred = model.predict_proba(X_test)`

**Comment by w4nderlust** [comment]
Good point @PeterPirog . If you set the output to be binary, you also get the raw probabilities together with the predictions (which are basically just a transformation of probabilities > threshold, and you can set the threshold in the output feature too if you want, by default is 0.5).
Does that work for you?

We could also make it so that users can define an activation function before the final output of the numerical feature, but the issue there would be that even if you do, say, a sigmoid to squash between 0 and 1, you'll still train with MSE loss (which may be fine, there are a few papers where it is shown that performance are comparable and in few cases even better than using cross entropy).

**Comment by PeterPirog** [comment]
@w4nderlust, I'm very glad to use your framework.  Can You give some suggestions how to set in ludwig metric for unballanced data because accuracy is bad option for it. I noticed some error for ROC AUC:
```
    return metrics.roc_curve(conditions, prediction_scores, pos_label,
TypeError: roc_curve() takes 2 positional arguments but 4 were given
```
Configuration is:


```
input_features:
    -
        name: Pclass
        type: category
    -
        name: Name
        type: text
        level: char
        encoder: parallel_cnn
    -
        name: Sex
        type: category
    -
        name: Age
        type: numerical
        preprocessing:
          missing_value_strategy: fill_with_mean
    -
        name: SibSp
        type: numerical
    -
        name: Parch
        type: numerical
    -
        name: Fare
        type: numerical
        preprocessing:
          missing_value_strategy: fill_with_mean

    -
        name: Embarked
        type: category

output_features:
    -
        name: Survived
        type: binary
```
