### ISSUE TITLE
[ray] Unify hyperopt config schema between ray tune and serial executors

### ISSUE THREAD

**Issue by tgaddair** [ludwig-ai/ludwig#1578]
Currently, the serial executor and Ray Tune follow different config conventions for hyperopt. For example:

```
  parameters:
    current_message.encoder:
      type: category
      values:
        - parallel_cnn
        - rnn
        - transformer
  sampler:
    type: grid
```

Ray Tune:

```
  sampler:
    type: ray
    num_samples: 3
  executor:
    type: ray
    time_budget_s: 1000
    cpu_resources_per_trial: 1
  parameters:
    current_message.encoder:
      space: grid_search
      values:
        - parallel_cnn
        - rnn
        - transformer
```

We should align on Ray Tune conventions.
