### ISSUE TITLE
[tf-legacy] input_features type mismatch in combiners

### ISSUE THREAD

**Issue by jeffreyftang** [ludwig-ai/ludwig#1617]
**Describe the bug**
On the `tf-legacy` branch, combiners expect `input_features` to be a list, but `build_inputs()` outputs an `OrderedDict`. In particular, this causes the `TabTransformerCombiner` to break.

**To Reproduce**
Attempt to train a model using the `titanic` dataset. Sample config:

```
input_features:
  - name: Pclass
    type: category
    column: Pclass
  - name: Sex
    type: category
    column: Sex
  - name: Age
    type: numerical
    column: Age
  - name: SibSp
    type: numerical
    column: SibSp
  - name: Parch
    type: numerical
    column: Parch
  - name: Ticket
    type: category
    column: Ticket
  - name: Fare
    type: numerical
    column: Fare
  - name: Cabin
    type: category
    column: Cabin
  - name: Embarked
    type: category
    column: Embarked
output_features:
  - name: Survived
    type: category
    column: Survived
combiner:
  type: tabtransformer
  num_layers: 1
  hidden_size: 256
  num_heads: 8
  transformer_fc_size: 256
  dropout: 0.1
  num_fc_layers: 0
  fc_size: 256
  use_bias: true
  weights_initializer: glorot_uniform
  bias_initializer: zeros
  fc_activation: relu
  fc_dropout: 0
  fc_residual: false
  reduce_output: concat
```

**Expected behavior**
Training succeeds.
