### ISSUE TITLE
Inconsistent learning rates shown in output when specifying learning rate in config 

### ISSUE THREAD

**Issue by dantreiman** [ludwig-ai/ludwig#1621]
When specifying the learning_rate parameter in the training section of the config, `description.json` shows a different default learning rate in the optimizer section:

config.yaml:
<img width="231" alt="Screen Shot 2021-12-21 at 4 46 42 PM" src="https://user-images.githubusercontent.com/687280/147016130-2856cfda-c399-4fc8-b79b-2fe96003b559.png">

description.json:
<img width="698" alt="Screen Shot 2021-12-21 at 4 47 04 PM" src="https://user-images.githubusercontent.com/687280/147016222-60e44fd7-fd92-474d-b73d-17c5c62d5954.png">

Expected behavior is that there is one learning rate, and if it is specified in the config it should match that.

**Comment by dantreiman** [comment]
Example config for repro (titanic example):
```
input_features:
    -
        name: Pclass
        type: category
    -
        name: Sex
        type: category
    -
        name: Age
        type: numerical
        preprocessing:
          missing_value_strategy: fill_with_mean
    -
        name: SibSp
        type: numerical
    -
        name: Parch
        type: numerical
    -
        name: Fare
        type: numerical
        preprocessing:
          missing_value_strategy: fill_with_mean
    -
        name: Embarked
        type: category

output_features:
    -
        name: Survived
        type: binary
        norm: null
        class_weights: 1
training:
  epochs: 100
  learning_rate: 0.05
  optimizer:
    type: sgd
  decay: false
  regularization_lambda: 0
```
