### ISSUE TITLE
Bi-directional RNN has error: mat1 and mat2 shapes cannot be multiplied

### ISSUE THREAD

**Issue by dantreiman** [ludwig-ai/ludwig#1735]
Training a character-level bidirectional RNN causes training to fail with error:
`RuntimeError: mat1 and mat2 shapes cannot be multiplied (128x1029 and 773x1)`

In the example below, the sender address field is encoded by an character-level encoder.  Setting encoder to 'rnn' works, but if `bidirectional: true` is present training fails on the first step.

Complete config below, data in spam_assassin.parquet.  Download: [spam_assassin.zip](https://github.com/ludwig-ai/ludwig/files/7982687/spam_assassin.zip)
```
input_features:
  - name: content
    type: text
    level: word
    encoder: parallel_cnn
  - name: internal_communication
    type: binary
  - name: external_communication
    type: binary
  - name: time_of_day
    type: numerical
  - name: n_recipients
    type: numerical
  - name: n_cc
    type: numerical
  - name: sender_address
    type: text
    level: char
    encoder: rnn
#    cell_type: lstm
    bidirectional: true
  - name: message_id
    type: text
    level: char
    encoder: rnn
output_features:
  - name: spam
    type: binary
training:
  decay: False
  learning_rate: 0.001
  validation_field: spam
  validation_metric: accuracy
```
