### ISSUE TITLE
RFC: Reorganize split configuration to support time-based split strategy

### ISSUE THREAD

**Issue by tgaddair** [ludwig-ai/ludwig#2129]
Current preprocessing configuration supports splitting based on a split column, split probabilities (train-val-test), and stratified splitting based on a category. Currently this is all flattened into the top-level of the preprocessing section:

```
preprocessing:
    force_split: false
    split_probabilities: [0.7, 0.1, 0.2]
    stratify: null
    category: {...}
    sequence: {...}
    text: {...}
```

The proposal here is to add the ability to split based on a date column such that the data is ordered by date (ascending) and then split according to the `split_probabilities`. For example, if `split_probabilities: [0.7, 0.1, 0.2]`, then the earliest 70% of the data will be used for training, the middle 10% used for validation, and the last 20% used for testing.

To achieve this, we could add a new param in this structure, but it starts to get confusing juggling mutually exclusive params. As such, the proposal would be to both add a new param and restructure this section to be more modular:

```
preprocessing:
    split:
        type: date
        column: created_ts
        probabilities: [0.7, 0.1, 0.2]
```

Existing split types would similarly be reworked:

Default:

```
preprocessing:
    split:
        type: random
        probabilities: [0.7, 0.1, 0.2]
```

Fixed:

```
preprocessing:
    split:
        type: fixed
        column: split
```

Stratified:

```
preprocessing:
    split:
        type: stratify
        column: region
        probabilities: [0.7, 0.1, 0.2]
```

One change in this approach would be that the user would need to be explicit about the split column, and splitting by fixed column would only happen if the user manually specifies it in the type.

**Comment by justinxzhao** [comment]
Related, but I think covered by this proposal: #1823.

For the `type: fixed` split, we should add additional fields to specify the values to use for different dataset splits.

```
preprocessing:
    split:
        type: fixed
        column: split
        train_values: [0] # Values in the split column that should be associated with the training split
        validation_values: [1] # Values in the split_column that should be associated with the validation split
        test_values:
```
