### ISSUE TITLE
RFC: Add configuration section for global feature parameters

### ISSUE THREAD

**Issue by tgaddair** [ludwig-ai/ludwig#2130]
Currently users can specify global preprocessing configuration on a per-feature basis. This is useful if users know they always want to apply certain transformations to their data for every feature of the same type. However, there is no equivalent mechanism for global encoder or decode parameters.

This proposal here is to allow the user to define global feature parameters for encoders and decoders in addition to the existing preprocessing params. Specifically:

1. Move existing feature preprocessing globals out of the `preprocessing` section such that the preprocessing section is only for things like splitting, etc.
2. Add a new `defaults` section that covers feature type defaults across all features.

These changes would also be affected by #2125, which would remove ambiguity between `encoder` and `decoder` params for the same feature type.

Example:

```
preprocessing:
    split:
        type: random
        probabilities: [0.7, 0.1, 0.2]
    oversample_minority: 0.5
defaults:
    category:
        preprocessing:        
            missing_value_strategy: fill_with_const
            fill_value: <UNK>
        encoder:
            type: sparse
        decoder:
            norm_params: null
            dropout: 0
            use_bias: true
        loss:
            type: softmax_cross_entropy
            confidence_penalty: 0
```

**Comment by tgaddair** [comment]
TSC accepted the proposal, with meta caveat that we need to make sure we think about schema changes holistically and try to avoid incremental schema changes that disrupt users ever version change.

**Comment by arnavgarg1** [comment]
@tgaddair I wanted to clarify what the behavior should be in the case where a parameter mentioned for a feature group in defaults is also mentioned elsewhere (say preprocessing or encoder). For e.g., if a user does something like:

```
input_features:
    -  name: title
        type: text
        preprocessing:
            word_length_limit: 20
    -  name: body
        type: text
        preprocessing:
            word_length_limit: 2000
defaults:
    text:
        preprocessing:
               word_length_limit: 10000
```

In this scenario, I'm thinking the behavior should be:

1. Overwrite default preprocessing with feature specific preprocessing, i.e., `word_length_limit` specified in input_features preprocessing overwrites and takes precedence over defaults
2. Log a warning with the value that will be used and a note that is is being overwritten in the config
