### ISSUE TITLE
[Hyperopt] Allow default shared parameter search spaces

### ISSUE THREAD

**Issue by arnavgarg1** [ludwig-ai/ludwig#2171]
It would be helpful to enable using a new `defaults` keyword within hyperopt to set default parameters for feature groups. This will help add search spaces more concisely for datasets with a large number of features while also reducing the search space to allow for a deeper search during hyperopt.

For e.g., a user should be able to add

`"defaults.input_features.text.cell_type": {"space": "choice", "categories": ["lstm", "gru"]}`

in their hyperopt search space so that all text input features use the sampled cell_type for that particular trial.

The API for this change will be as follows: `defaults.<feature_group>.<feature_type>.<parameter>`, where:

- `feature_group`: either input_features or output_features to distinguish which features to apply this to
- `feature_type`: the feature type in question, for e.g., text/category/sequence etc.
- `parameter`: the parameter that one wants to search over for that particular feature type, for e.g., vocab_size for text

Example Configuration:

```yaml
hyperopt:
    goal: minimize
    parameters:
        trainer.learning_rate:
            lower: 0.0001
            upper: 0.01
            space: loguniform
        defaults.input_features.text.cell_type:
            space: choice
            categories: ["lstm", "rnn", "gru"]
        defaults.output_features.category.vocab_size:
            space: randint
            lower: 4
            upper: 8
        ....
    ....
```
