### ISSUE TITLE
Add JSONSchema for global defaults section of Ludwig config

### ISSUE THREAD

**Issue by arnavgarg1** [ludwig-ai/ludwig#2222]
We should update the `__init__.py` in schema to validate the schema for the global defaults section of Ludwig. The updated config will look like this

```yaml
preprocessing:
    split:
        type: random
        probabilities: [0.7, 0.1, 0.2]
    oversample_minority: 0.5
defaults:
    category:
        preprocessing:        
            missing_value_strategy: fill_with_const
            fill_value: <UNK>
        encoder:
            type: sparse
        decoder:
            norm_params: null
            dropout: 0
            use_bias: true
        loss:
            type: softmax_cross_entropy
            confidence_penalty: 0
```

For more information, look at:

- Issue: https://github.com/ludwig-ai/ludwig/issues/2130
- PR: https://github.com/ludwig-ai/ludwig/pull/2208
