### ISSUE TITLE
"AttributeError: module 'horovod.torch' has no attribute 'init'"

### ISSUE THREAD

**Issue by andife** [ludwig-ai/ludwig#2406]
**Describe the bug**
"AttributeError: module 'horovod.torch' has no attribute 'init'"

**To Reproduce**

Shipped simple_model_training example with backend "horovod"
`
examples/titanic$ python simple_model_training.py
`
```
yaml:
input_features:
    - name: Pclass
      type: category
    - name: Sex
      type: category
    - name: Age
      type: number
      preprocessing:
          missing_value_strategy: fill_with_mean
    - name: SibSp
      type: number
    - name: Parch
      type: number
    - name: Fare
      type: number
      preprocessing:
          missing_value_strategy: fill_with_mean
    - name: Embarked
      type: category

output_features:
    - name: Survived
      type: binary

backend:
  type: horovod

```

yaml and 

**Expected behavior**
just work

**Error log:**

(ludwigai2) andi@erde:~/Andreas/dev/ludwigexample/examples/titanic$ python simple_model_training.py 
NumExpr defaulting to 4 threads.
Extension horovod.torch has not been built: /home/andi/miniforge-pypy3/envs/ludwigai2/lib/python3.8/site-packages/horovod/torch/mpi_lib/_mpi_lib.cpython-38-x86_64-linux-gnu.so not found
If this is not expected, reinstall Horovod with HOROVOD_WITH_PYTORCH=1 to debug the build error.
Warning! MPI libs are missing, but python applications are still available.
Traceback (most recent call last):
  File "simple_model_training.py", line 23, in <module>
    model = LudwigModel(config="./model1_config.yaml", logging_level=logging.INFO)
  File "/home/andi/miniforge-pypy3/envs/ludwigai2/lib/python3.8/site-packages/ludwig/api.py", line 217, in __init__
    self.backend = initialize_backend(backend or self.config.get("backend"))
  File "/home/andi/miniforge-pypy3/envs/ludwigai2/lib/python3.8/site-packages/ludwig/backend/__init__.py", line 103, in initialize_backend
    backend.initialize()
  File "/home/andi/miniforge-pypy3/envs/ludwigai2/lib/python3.8/site-packages/ludwig/backend/horovod.py", line 34, in initialize
    self._horovod = initialize_horovod()
  File "/home/andi/miniforge-pypy3/envs/ludwigai2/lib/python3.8/site-packages/ludwig/utils/horovod_utils.py", line 36, in initialize_horovod
    _HVD.init()

**Environment (please complete the following information):**

- OS: Ubuntu 
- Version 22.04.1 LTS
- Python version: 2.8
- Ludwig version: 0.5.5
- ray: 1.13.0
- torch: 1.12.1+cu102

**Additional context**
