### ISSUE TITLE
Encountered Ray Tune error: list index out of range

### ISSUE THREAD

**Issue by Exitare** [ludwig-ai/ludwig#3134]
**Describe the bug**
Ludwig hyperopt is stopping due to this error.
raise RuntimeError(f"Encountered Ray Tune error: {e}")
RuntimeError: Encountered Ray Tune error: list index out of range
The hyper opt should improve a regression problem, predicting a continuous variable.

I don't know what I am doing wrong. 
I used this [page](https://ludwig.ai/latest/configuration/hyperparameter_optimization/#hyperopt-configuration-parameters)
to create a working version of my config, but it doesn't seem to work.

**To Reproduce**
This is my yaml config file

```input_features:
- name: ER
  type: numerical
output_features:
- name: CK19
  type: numerical
combiner:
  type: concat
  num_fc_layers: 1

training:
  learning_rate: 0.001
  optimizer:
    type: adam

hyperopt:
  search_alg:
    type: random
    executor:
      type: ray
      num_samples: 12
  metric: mean_absolute_error
  split: validation
  output_feature: CK19
  goal: minimize
  parameters:
    learning_rate:
      type: float
      space: loguniform
      lower: 0.0001
      upper: 0.1
    num_fc_layers:
      space: randint
      lower: 1
      upper: 4

```

This is how I call the hyper opt:
`ludwig hyperopt --dataset "dataset.csv" --config "final_config.yaml`

**Expected behavior**
I expected the tuner to run and perform hyper opt and not encounter a list index out of range exception.

**Environment (please complete the following information):**

- OS: Mac OS Ventura 13.2
- Python version: 3.9.4
- Ludwig version : 0.6.4

**Additional context*

This is the whole error message:

```
Traceback (most recent call last):
  File "/venv/bin/ludwig", line 8, in <module>
    sys.exit(main())
  File "/venv/lib/python3.9/site-packages/ludwig/cli.py", line 172, in main
    CLI()
  File "/venv/lib/python3.9/site-packages/ludwig/cli.py", line 67, in __init__
    getattr(self, args.command)()
  File "/venv/lib/python3.9/site-packages/ludwig/cli.py", line 92, in hyperopt
    hyperopt_cli.cli(sys.argv[2:])
  File "/venv/lib/python3.9/site-packages/ludwig/hyperopt_cli.py", line 413, in cli
    hyperopt_cli(**vars(args))
  File "/venv/lib/python3.9/site-packages/ludwig/hyperopt_cli.py", line 161, in hyperopt_cli
    return hyperopt(
  File "/venv/lib/python3.9/site-packages/ludwig/hyperopt/run.py", line 361, in hyperopt
    hyperopt_results = hyperopt_executor.execute(
  File "/venv/lib/python3.9/site-packages/ludwig/hyperopt/execution.py", line 839, in execute
    raise RuntimeError(f"Encountered Ray Tune error: {e}")
RuntimeError: Encountered Ray Tune error: list index out of range
```

**Comment by arnavgarg1** [comment]
Hey @Exitare, I think the config generally looks ok except for a few things (that are probably causing problems):

```
input_features:
    - name: ER
       type: numerical
output_features:
    - name: CK19
       type: numerical

combiner:
  type: concat
  num_fc_layers: 1

training:
  learning_rate: 0.001
  optimizer:
    type: adam

hyperopt:
  search_alg:
    type: random
    executor:
      type: ray
      num_samples: 12
  metric: mean_absolute_error
  split: validation
  output_feature: CK19
  goal: minimize
  parameters:
    trainer.learning_rate:
      type: float
      space: loguniform
      lower: 0.0001
      upper: 0.1
    combiner.num_fc_layers:
      space: randint
      lower: 1
      upper: 4
```

The main changes are:
1. Formatting input/output features to have the correct indentation
2. When defining parameter spaces, we need to reference them by the section in consideration. For e.g., `learning_rate` is a valid parameter, but specifically it belongs to the trainer section. So, it requires a rename from `learning_rate` to `trainer.learning_rate`. Similarly, `num_fc_layers` needs to be `combiner.num_fc_layers`. The reason this also matters is because some parameters like `num_fc_layers` can belong to the encoder, the combiner, or the decoder, so we want to make sure that we specify what section of the Ludwig config we're specifically trying to hyperopt over.

Let me know if this fixes the issue!
