### ISSUE TITLE
Out of Memory Error Running llama2_7b_finetuning_4bit Example

### ISSUE THREAD

**Issue by charleslbryant** [ludwig-ai/ludwig#3583]
**Describe the bug**
Running the "Llama2-7b Fine-Tuning with 4bit Quantization" example notebook in Colab fails with the following error:

`OutOfMemoryError: CUDA out of memory. Tried to allocate 86.00 MiB (GPU 0; 14.75 GiB total capacity; 13.37 GiB already allocated; 80.81 MiB free; 13.79 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

I am new to Ludwig and AI in general so this may be user error.

**To Reproduce**

1. Open the notebook in Colab - https://colab.research.google.com/drive/1c3AO8l_H6V_x37RwQ8V7M6A-RmcBf2tG?usp=sharing
2. Add my HUGGING_FACE_HUB_TOKEN to code frame 2
3. Run the notebook
4. Run ends in error

```
INFO:ludwig.trainers.trainer:Starting with step 0, epoch: 0
Training:  18%|█▊        | 1935/10920 [17:45<1:13:32,  2.04it/s, loss=0.081]
---------------------------------------------------------------------------
OutOfMemoryError                          Traceback (most recent call last)
<ipython-input-4-f24794477812> in <cell line: 6>()
      4 
      5 model = LudwigModel(config=config, logging_level=logging.INFO)
----> 6 results = model.train(dataset="ludwig://alpaca")
      7 print(results)

27 frames
/usr/local/lib/python3.10/dist-packages/bitsandbytes/functional.py in dequantize_4bit(A, quant_state, absmax, out, blocksize, quant_type)
    906 
    907     if out is None:
--> 908         out = torch.empty(shape, dtype=dtype, device=A.device)
    909 
    910     n = out.numel()

OutOfMemoryError: CUDA out of memory. Tried to allocate 86.00 MiB (GPU 0; 14.75 GiB total capacity; 13.37 GiB already allocated; 80.81 MiB free; 13.79 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

After 3 runs in new Colab sessions it consistently fails at the same point.

```
INFO:ludwig.trainers.trainer:Starting with step 0, epoch: 0
Training:  18%|█▊        | 1935/10920
```

Running the [example notebook](https://ludwig.ai/latest/examples/llms/llm_finetuning/) out the box. No other changes were made to the notebook or config.

```
model_type: llm
base_model: meta-llama/Llama-2-7b-hf

quantization:
  bits: 4

adapter:
  type: lora

prompt:
  template: |
    ### Instruction:
    {instruction}

    ### Input:
    {input}

    ### Response:

input_features:
  - name: prompt
    type: text

output_features:
  - name: output
    type: text

trainer:
  type: finetune
  learning_rate: 0.0001
  batch_size: 1
  gradient_accumulation_steps: 16
  epochs: 3
  learning_rate_scheduler:
    warmup_fraction: 0.01

preprocessing:
  sample_ratio: 0.1
```

**Expected behavior**
After watching [video](https://www.youtube.com/watch?v=g68qlo9Izf0) by Ludwig team that explained how to fine-tune Llama-2-7b on a single T4 GPU, I tried running the [example notebook](https://github.com/ludwig-ai/ludwig/tree/master/examples/llama2_7b_finetuning_4bit) linked in the Ludwig GitHub repository and expected the model to be fine-tuned for instruction on the Alpaca dataset.

*FYI, the notebook from the video worked fine for me, but it uses a smaller data set - https://colab.research.google.com/drive/1Ly01S--kUwkKQalE-75skalp-ftwl0fE?usp=sharing.*

**Environment (please complete the following information):**

- OS: Google Colab - Linux Ubuntu
- Python version: 3.10
- Ludwig version: 0.8.2

**Additional context**

- Random seed: 42
- Dataset: ludwig://alpaca
- Data format: ludwig
- Torch version: 2.0.1+cu118
- Compute:
  - GPU Type: Tesla T4
  - GPUs per node: 1
  - Number of nodes: 1
- System RAM: 51.0 GB
- GPU RAM: 15.0 GB
- Disk: 166.8 GB

**Comment by tgaddair** [comment]
Hey @charleslbryant, thanks for reporting this issue. I suspect this was due to a change in the default `max_sequence_length` we made in v0.8.2 last week. Can you try changing the features section to the following:

```
input_features:
  - name: prompt
    type: text
    preprocessing:
      max_sequence_length: 256

output_features:
  - name: output
    type: text
    preprocessing:
      max_sequence_length: 256
```

That should restore the behavior of the old defaults that were previously working.
