### ISSUE TITLE
Code Llama Support not fully working yet

### ISSUE THREAD

**Issue by DevHorn** [ludwig-ai/ludwig#3605]
**Describe the bug**
When trying to fine-Tune Code-LLama Instruct 7B with Ludwig I get a RuntimeError: Could not infer dtype of NoneType

**To Reproduce**

1. Use the Notebook that Ludwig used for the Deeplearning.ai workshop with this yaml-congfig instead. This will load code llama and a few fine tuning parameters.
2. Replace the code block with the yaml configuration with the one I provide.
3. Running the training loop of the model will produce the error.

Notebook is found at: https://pbase.ai/FineTuneLlama
Data is imported in the notebook....

The Yaml config file: 
```

config = yaml.safe_load(
  """
  model_type: llm
  base_model: codellama/CodeLlama-7b-Instruct-hf

  input_features:
    - name: instruction
      type: text

  output_features:
    - name: output
      type: text

  prompt:
    template: >-
      Below is a java class. Your task is to write a appropriate test class
      for it. Only write sensible, correct tests.

      ### Input:
      {instruction}

      ### Response:

  generation:
    temperature: 0.1 # Temperature is used to control the randomness of predictions.
    max_new_tokens: 512

  quantization:
    bits: 4

  generation:
    temperature: 0.1 # Temperature is used to control the randomness of predictions.
    max_new_tokens: 2048

  adapter:
    type: lora

  trainer:
    type: finetune
  epochs: 5
  batch_size: 1
  eval_batch_size: 2
  gradient_accumulation_steps: 8
  learning_rate: 0.00001
  optimizer:
    type: adam
    params:
      eps: 1.e-8
      betas:
        - 0.9
        - 0.999
      weight_decay: 0
  learning_rate_scheduler:
    warmup_fraction: 0.03
    reduce_on_plateau: 0

  """
)




model = LudwigModel(config=config, logging_level=logging.DEBUG)
results = model.train(dataset=df)

```

### **Expected behavior**
Training Loop starts and runs through

**Screenshots**

**Environment (please complete the following information):**
Google Colab

**Additional context**
This was "supposed" to be the fix for my problem but it has done nothing to it:
https://github.com/ludwig-ai/ludwig/pull/3598
