### ISSUE TITLE
Add support for visual language model fine-tuning (IDEFICS, etc.)

### ISSUE THREAD

**Issue by tgaddair** [ludwig-ai/ludwig#3656]
IDEFICS: https://huggingface.co/blog/idefics

Example config:

```
input_features:
  - name: prompt
    type: text
  - name: img
    type: image
output_features:
  - name: response
    type: text
```
