### ISSUE TITLE
Ray `session.get_dataset_shard` deprecation "warning" stops training

### ISSUE THREAD

**Issue by trevenrawr** [ludwig-ai/ludwig#3714]
**Describe the bug**
While trying to recreate https://ludwig.ai/0.8/examples/llms/llm_text_generation/ on my setup using proprietary data, I ran into a Ray deprecation "warning" that continued to crash my training runs.  It appears to be complaining about something that changed as of Ray 2.3, but I saw that Ludwig allows ray versions from `2.2.0` to `<2.5` (I'm using `2.4`), so it seems strange that it would be a syntax issue...

Data shape:
`jsonl` (one dictionary/map per line; flat with column labels as keys; seems to load okay)

Training config:
```
model_type: llm
base_model: meta-llama/Llama-2-7b-hf

adapter:
  type: lora

prompt:
  template: |
    Below is an instruction that describes a task. Write a response that appropriately completes the request.

    ### Instruction:
    Generate 2 questions from the context:

    Context: {context}

    ### Response:

input_features:
  - name: prompt
    type: text
    preprocessing:
      max_sequence_length: 512

output_features:
  - name: questions
    type: text
    preprocessing:
      max_sequence_length: 256

trainer:
  type: finetune
  learning_rate: 0.0003
  batch_size: 1
  gradient_accumulation_steps: 16
  epochs: 3
  learning_rate_scheduler:
    warmup_fraction: 0.01

postprocessing:
  sample_ratio: 0.1
```

**To Reproduce**
1. Submit `experiment` job to Ray cluster
2. Data gets 
3. Model gets loaded
4. Training begins... then 

```
620  File "/home/ml/virtualenv/lib/python3.10/site-packages/ludwig/backend/ray.py", line 501, in <lambda>
621    lambda config: train_fn(**config),
622  File "/home/ml/virtualenv/lib/python3.10/site-packages/ludwig/backend/ray.py", line 193, in train_fn
623    val_shard = RayDatasetShard(val_shard, features, training_set_metadata)
624  File "/home/ml/virtualenv/lib/python3.10/site-packages/ludwig/data/dataset/ray.py", line 244, in __init__
625    self.create_epoch_iter()
626  File "/home/ml/virtualenv/lib/python3.10/site-packages/ludwig/data/dataset/ray.py", line 268, in create_epoch_iter
627    self.epoch_iter = self.dataset_shard.repeat().iter_epochs()
628  File "/home/ml/virtualenv/lib/python3.10/site-packages/ray/data/_internal/dataset_iterator/dataset_iterator_impl.py", line 48, in __getattr__
629    raise DeprecationWarning(
630DeprecationWarning: session.get_dataset_shard returns a ray.data.DatasetIterator instead of a Dataset/DatasetPipeline as of Ray v2.3. Use iter_torch_batches(), to_tf(), or iter_batches() to iterate over one epoch. See https://docs.ray.io/en/latest/data/api/dataset_iterator.html for full DatasetIterator docs.
6312023-10-11 02:07:43,868	ERROR tune.py:941 -- Trials did not complete: [TorchTrainer_e1cf1_00000]
```
...
```
654The above exception was the direct cause of the following exception:
655
656Traceback (most recent call last):
657  File "/home/ml/virtualenv/bin/ludwig", line 8, in <module>
658    sys.exit(main())
659  File "/home/ml/virtualenv/lib/python3.10/site-packages/ludwig/cli.py", line 191, in main
660    CLI()
661  File "/home/ml/virtualenv/lib/python3.10/site-packages/ludwig/cli.py", line 71, in __init__
662    getattr(self, args.command)()
663  File "/home/ml/virtualenv/lib/python3.10/site-packages/ludwig/cli.py", line 96, in experiment
664    experiment.cli(sys.argv[2:])
665  File "/home/ml/virtualenv/lib/python3.10/site-packages/ludwig/experiment.py", line 528, in cli
666    experiment_cli(**vars(args))
667  File "/home/ml/virtualenv/lib/python3.10/site-packages/ludwig/experiment.py", line 217, in experiment_cli
668    (eval_stats, train_stats, preprocessed_data, output_directory) = model.experiment(
669  File "/home/ml/virtualenv/lib/python3.10/site-packages/ludwig/api.py", line 1337, in experiment
670    (train_stats, preprocessed_data, output_directory) = self.train(
671  File "/home/ml/virtualenv/lib/python3.10/site-packages/ludwig/api.py", line 640, in train
672    train_stats = trainer.train(
673  File "/home/ml/virtualenv/lib/python3.10/site-packages/ludwig/backend/ray.py", line 500, in train
674    trainer_results = runner.run(
675  File "/home/ml/virtualenv/lib/python3.10/site-packages/ludwig/backend/ray.py", line 439, in run
676    return trainer.fit()
677  File "/home/ml/virtualenv/lib/python3.10/site-packages/ray/train/base_trainer.py", line 614, in fit
678    raise TrainingFailedError(
```

I tried setting `epochs: 1` but that didn't seem to work around the `self.create_epoch_iter()` call that is part of the stack trace here.  Also fiddled with batch size to no avail, but since this isn't an OOM, I didn't expect many of the config options to make a difference anyway.

**Expected behavior**
I expected it to train without a hitch 😅 

**Screenshots**

**Environment (please complete the following information):**

- Amazon Linux 2 (container) running via Docker (with NVIDIA container toolkit) on a CentOS 7 AMI
- CUDA 12.1
- Python 3.10.13
- `ludwig[full]==0.8.4`
- `ray==2.4.0`
- `torch==2.1.0`

**Additional context**
One of the biggest differences with my setup is the OS because I have to build all my own images (from scratch).  It seems unlikely that this kind of error would arise due to my OS, though; the deprecation warning seems more related to syntax than anything.  It appears that you're building your GPU images from ray 2.3.1 here: https://github.com/ludwig-ai/ludwig/blob/master/docker/ludwig-ray-gpu/Dockerfile#L12 so I'll probably try pinning Ray in my setup to `2.3.1` as a first pass to see if that solves the issue.

P.S. Ray Train went GA (stable API) as of `2.7`; are there plans to upgrade?  I'm definitely interested (and hopefully able to make time) to help out with such an endeavor!
