### ISSUE TITLE
Finetuning job is stopping right at Preprocessing

### ISSUE THREAD

**Issue by tu-trinh** [ludwig-ai/ludwig#3754]
**Describe the bug**
I've created an environment specifically for Ludwig as shown in this example [notebook](https://colab.research.google.com/drive/1i_8A1n__b7ljRWHzIsAdhO7u7r49vUm4) and tried to finetune Mistral in it. I tried both the original `mistralai/Mistral-7B-Instruct-v0.1` and the sharded `alexsherstinsky/Mistral-7B-v0.1-sharded` that is used in the example notebook. However, both attempts stop right at PREPROCESSING and do not go further, in fact one of them I left to run overnight and it was still at PREPROCESSING. No visible errors otherwise. I am running both on a GPU.

**To Reproduce**
The code:
```
import pandas as pd
import logging
from ludwig.api import LudwigModel
import argparse
import yaml

def main():
    with open(f"./ludwig_yamls/mistral.yaml", "r") as f:
        config = yaml.safe_load(f)
    df = pd.read_csv("../data/classification/trainable_data.csv")
    model = LudwigModel(config = config, logging_level = logging.INFO)
    results = model.train(dataset = df)
    print(results)

if __name__ == "__main__":
    main()
```

The yaml file:
```
model_type: llm
# base_model: mistralai/Mistral-7B-Instruct-v0.1
base_model: alexsherstinsky/Mistral-7B-v0.1-sharded

input_features:
  - name: passage
    type: text

output_features:
  - name: answer
    type: text

prompt:
  template: |-
    some long template here, ~3000 characters

generation:
  temperature: 0.0
  max_new_tokens: 410

adapter:
  type: lora

quantization:
  bits: 4

preprocessing:
  split:
    type: random
    probabilities:
    - 0.9
    - 0.05
    - 0.05

trainer:
  type: finetune
  epochs: 10
  batch_size: 1
  eval_batch_size: 1
  gradient_accumulation_steps: 16
  enable_gradient_checkpointing: true
  learning_rate: 0.00003
  learning_rate_scheduler:
    warmup_fraction: 0.03
```
The data: available [here](https://gist.github.com/tu-trinh/08e36b3f3d55c201ef89689a0a0b3fbd)

**Expected behavior**
I just expect it to run normally and complete the finetuning job 😄 

**Screenshots**
[Here](https://gist.github.com/tu-trinh/62b7c88f49d334088984b693420ec1b7) is the output and where it is getting stuck. For one of the runs I specify `CUDA_VISIBLE_DEVICES=<some number>` but I think this output is the same for both of them; they're both getting stuck here anyways.

**Environment (please complete the following information):**
- OS (from `/etc/os-release`)
```
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
```
- Python version: 3.8.18
- Ludwig version: 0.8.6
