### ISSUE TITLE
RuntimeError in Model Training on Predibase with Ludwig: Data Type Mismatch

### ISSUE THREAD

**Issue by bi1101** [ludwig-ai/ludwig#3914]
**Describe the bug**
When trying to fine-tune a model on Predibase using Ludwig with a specific configuration, I encountered a `RuntimeError` related to a mismatch in data types (Half and Float) during model training.

**To Reproduce**
1. Set up a Ludwig CUSTOM ECD model configuration with the following input and output features:
   ```yaml
   input_features:
     - name: Essay and Question
       type: text
       encoder:
         type: llm
         adapter:
           type: lora
         base_model: mistralai/Mistral-7B-Instruct-v0.1
         quantization:
           bits: 4
       column: Essay and Question
   output_features:
     - name: Answer All Parts of the Question Text
       type: category
       column: Answer All Parts of the Question Text
   ```
2. Initiate model training on the Predibase platform.
3. Encounter the following error during training:
   ```
   Error in model training
   RuntimeError: mat1 and mat2 must have the same dtype, but got Half and Float. [ID: 44befd2b2d061584f9f2c272a0cb7b79]
   ```

**Expected behavior**
Successful fine-tuning job.

**Screenshots**
![image](https://github.com/ludwig-ai/ludwig/assets/15710921/4b4b6fb4-1413-4582-8215-7613a9229d61)

**Environment:**
- Predibase Platform

**Dataset:** 
[Score_classification_task.csv](https://github.com/ludwig-ai/ludwig/files/14034012/Score_classification_task.csv)

Any insights or fixes for this issue would be greatly appreciated.
