### ISSUE TITLE
You are calling `save_pretrained` to a 4-bit converted model, but your `bitsandbytes` version doesn't support it.

### ISSUE THREAD

**Issue by shripadk** [ludwig-ai/ludwig#3951]
**Describe the bug**

I have enabled 4-bit quantization for fine tuning mistralai/Mistral-7B-v0.1. Seems like Ludwig 0.10.1 depends on [bitsandbytes < 0.41.0](https://github.com/ludwig-ai/ludwig/blob/master/requirements.txt#L53). But when I run the trainer I get the following warning:

```bash
You are calling `save_pretrained` to a 4-bit converted model, but your `bitsandbytes` version doesn't support it. 
If you want to save 4-bit models, make sure to have `bitsandbytes>=0.41.3` installed.
```

**To Reproduce**

1. Install Ludwig

```bash
pip install ludwig[full]
```

2. Config file (`model.yaml`):

```yaml
model_type: llm
base_model: mistralai/Mistral-7B-v0.1

quantization:
  bits: 4

adapter:
  type: lora

prompt:
  template: |
    ### Instruction:
    {instruction}

    ### Input:
    {input}

    ### Response:

input_features:
  - name: prompt
    type: text

output_features:
  - name: output
    type: text

generation:
  temperature: 0.1

trainer:
  type: finetune
  epochs: 3
  optimizer:
    type: paged_adam
  batch_size: 1
  eval_steps: 100
  learning_rate: 0.0002
  eval_batch_size: 2
  steps_per_checkpoint: 1000
  learning_rate_scheduler:
    decay: cosine
    warmup_fraction: 0.03
  gradient_accumulation_steps: 16
  enable_gradient_checkpointing: true

preprocessing:
  sample_ratio: 0.1
```

3. Train the model:

```bash
ludwig train --config model.yaml --dataset "ludwig://alpaca"
```

**Expected behavior**
Should not show the warning on `bitsandbytes` version not supporting `save_pretrained` for 4-bit quantization.

**Environment (please complete the following information):**

- OS: Linux
- Version: 6.7.6-arch1-1
- Python: 3.10.8
- Ludwig: v0.10.1

@alexsherstinsky
