### ISSUE TITLE
AttributeError: module 'torchtext' has no attribute 'transforms'

### ISSUE THREAD

**Issue by nqbao** [ludwig-ai/ludwig#4015]
**Describe the bug**
I got this error while trying to train a model with encoder = bert

**To Reproduce**

```
trainer:
    validation_field: engagement_label
    validation_metric: roc_auc
    early_stop: 10

input_features:
    - name: text1
      type: text
      encoder: 
          type: bert
    - name: text2
      type: text
      encoder: 
          type: bert

output_features:
    - name: engagement_label
      type: binary
      threshold: 0.6
```

**Expected behavior**
model is trained with no error

**Screenshots**
n/a

**Environment (please complete the following information):**

- OS: \[e.g. iOS\]
- Version \[e.g. 22\]
- Python 3.11.8
- ludwig==0.10.3

**Additional context**
