### ISSUE TITLE
Conditional Random Field (CRF) Sequence Decoder

### ISSUE THREAD

**Issue by BeWe11** [ludwig-ai/ludwig#494]
The current example for Name Entity Extraction is given as the following model definition:
```yaml
input_features:
    -
        name: utterance
        type: text
        level: word
        encoder: rnn
        cell_type: lstm
        reduce_output: null
        preprocessing:
          word_format: space

output_features:
    -
        name: tag
        type: sequence
        decoder: tagger
```
This works ok, but if Ludwig had a CRF-Decoding layer, one could build state-of-the-art Bi-LSTM+CRF models (like https://arxiv.org/pdf/1508.01991.pdf) in a single simple Ludwig model definition. Any chance CRF decoding is coming to Ludwig any time soon?
