### ISSUE TITLE
How to format model architecture for image captioning with multiple captions per image?

### ISSUE THREAD

**Issue by StuckinPhD** [ludwig-ai/ludwig#745]
Hi,

Im trying to perform image captioning following the example here: https://ludwig-ai.github.io/ludwig-docs/examples/#image-captioning

The example is written for a single caption against each image with the model definition being:

```
input_features:
    -
        name: image_path
        type: image
        encoder: stacked_cnn

output_features:
    -
        name: caption
        type: text
        level: word
        decoder: generator
        cell_type: lstm
```

But I'm using the flickr8k dataset that has 5 captions per image. Is it possible to use such a dataset with Ludwig or do I have to strip the rest of the captions and use only one?

```
[image 1]    [caption 1]    [caption 2]    [caption 3]    [caption 4]    [caption 5]    
[image 2]    [caption 1]    [caption 2]    [caption 3]    [caption 4]    [caption 5]    
[image 3]    [caption 1]    [caption 2]    [caption 3]    [caption 4]    [caption 5]    
...
...
```
Thanks.
